ARM: backport a bunch of mm changes for erratum 798181
The following patches are backported from stable/master to allow the workaround for erratum 798181 to apply and make sense.
 2013-03-26 catalin.marinas@arm.com ARM: 7684/1: errata: Workaround for Cortex-A15 erratum 798181 (TLBI/DSB operations)

  ARM: 7445/1: mm: update CONTEXTIDR register to contain PID of current process

  This patch introduces a new Kconfig option which, when enabled, causes
  the kernel to write the PID of the current task into the PROCID field
  of the CONTEXTIDR on context switch. This is useful when analysing
  hardware trace, since writes to this register can be configured to emit
  an event into the trace stream.

  The thread notifier for writing the PID is deliberately kept separate
  from the ASID-writing code so that we can support newer processors using
  LPAE, where the ASID is stored in TTBR0. As such, the switch_mm code is
  updated to perform a read-modify-write sequence to ensure that we don't
  clobber the PID on CPUs using the classic 2-level page tables.

  Signed-off-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 2nd commit message:

  ARM: 7502/1: contextidr: avoid using bfi instruction during notifier

  The bfi instruction is not available on ARMv6, so instead use an and/orr
  sequence in the contextidr_notifier. This gets rid of the assembler
  error:

    Assembler messages:
    Error: selected processor does not support ARM mode `bfi r3,r2,#0,#8'

  Reported-by: Arnd Bergmann <arnd@arndb.de>
  Signed-off-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 3rd commit message:

  ARM: mm: remove IPI broadcasting on ASID rollover

  ASIDs are allocated to MMU contexts based on a rolling counter. This
  means that after 255 allocations we must invalidate all existing ASIDs
  via an expensive IPI mechanism to synchronise all of the online CPUs and
  ensure that all tasks execute with an ASID from the new generation.

  This patch changes the rollover behaviour so that we rely instead on the
  hardware broadcasting of the TLB invalidation to avoid the IPI calls.
  This works by keeping track of the active ASID on each core, which is
  then reserved in the case of a rollover so that currently scheduled
  tasks can continue to run. For cores without hardware TLB broadcasting,
  we keep track of pending flushes in a cpumask, so cores can flush their
  local TLB before scheduling a new mm.

  Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
  Tested-by: Marc Zyngier <marc.zyngier@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>

  # This is the 4th commit message:

  ARM: mm: avoid taking ASID spinlock on fastpath

  When scheduling a new mm, we take a spinlock so that we can:

    1. Safely allocate a new ASID, if required
    2. Update our active_asids field without worrying about parallel
       updates to reserved_asids
    3. Ensure that we flush our local TLB, if required

  However, this has the nasty affect of serialising context-switch across
  all CPUs in the system. The usual (fast) case is where the next mm has
  a valid ASID for the current generation. In such a scenario, we can
  avoid taking the lock and instead use atomic64_xchg to update the
  active_asids variable for the current CPU. If a rollover occurs on
  another CPU (which would take the lock), when copying the active_asids
  into the reserved_asids another atomic64_xchg is used to replace each
  active_asids with 0. The fast path can then detect this case and fall
  back to spinning on the lock.

  Tested-by: Marc Zyngier <marc.zyngier@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>

  # This is the 5th commit message:

  ARM: mm: use bitmap operations when allocating new ASIDs

  When allocating a new ASID, we must take care not to re-assign a
  reserved ASID-value to a new mm. This requires us to check each
  candidate ASID against those currently reserved by other cores before
  assigning a new ASID to the current mm.

  This patch improves the ASID allocation algorithm by using a
  bitmap-based approach. Rather than iterating over the reserved ASID
  array for each candidate ASID, we simply find the first zero bit,
  ensuring that those indices corresponding to reserved ASIDs are set
  when flushing during a rollover event.

  Tested-by: Marc Zyngier <marc.zyngier@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>

  # This is the 6th commit message:

  ARM: 7582/2: rename kvm_seq to vmalloc_seq so to avoid confusion with KVM

  The kvm_seq value has nothing to do what so ever with this other KVM.
  Given that KVM support on ARM is imminent, it's best to rename kvm_seq
  into something else to clearly identify what it is about i.e. a sequence
  number for vmalloc section mappings.

  Signed-off-by: Nicolas Pitre <nico@linaro.org>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 7th commit message:

  ARM: 7649/1: mm: mm->context.id fix for big-endian

  Since the new ASID code in b5466f8728527a05a493cc4abe9e6f034a1bbaab
  ("ARM: mm: remove IPI broadcasting on ASID rollover") was changed to
  use 64bit operations it has broken the BE operation due to an issue
  with the MM code accessing sub-fields of mm->context.id.

  When running in BE mode we see the values in mm->context.id are stored
  with the highest value first, so the LDR in the arch/arm/mm/proc-macros.S
  reads the wrong part of this field. To resolve this, change the LDR in
  the mmid macro to load from +4.

  Acked-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Ben Dooks <ben.dooks@codethink.co.uk>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 8th commit message:

  ARM: 7658/1: mm: fix race updating mm->context.id on ASID rollover

  If a thread triggers an ASID rollover, other threads of the same process
  must be made to wait until the mm->context.id for the shared mm_struct
  has been updated to new generation and associated book-keeping (e.g.
  TLB invalidation) has ben performed.

  However, there is a *tiny* window where both mm->context.id and the
  relevant active_asids entry are updated to the new generation, but the
  TLB flush has not been performed, which could allow another thread to
  return to userspace with a dirty TLB, potentially leading to data
  corruption. In reality this will never occur because one CPU would need
  to perform a context-switch in the time it takes another to do a couple
  of atomic test/set operations but we should plug the race anyway.

  This patch moves the active_asids update until after the potential TLB
  flush on context-switch.

  Cc: <stable@vger.kernel.org> # 3.8
  Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 9th commit message:

  ARM: 7659/1: mm: make mm->context.id an atomic64_t variable

  mm->context.id is updated under asid_lock when a new ASID is allocated
  to an mm_struct. However, it is also read without the lock when a task
  is being scheduled and checking whether or not the current ASID
  generation is up-to-date.

  If two threads of the same process are being scheduled in parallel and
  the bottom bits of the generation in their mm->context.id match the
  current generation (that is, the mm_struct has not been used for ~2^24
  rollovers) then the non-atomic, lockless access to mm->context.id may
  yield the incorrect ASID.

  This patch fixes this issue by making mm->context.id and atomic64_t,
  ensuring that the generation is always read consistently. For code that
  only requires access to the ASID bits (e.g. TLB flushing by mm), then
  the value is accessed directly, which GCC converts to an ldrb.

  Cc: <stable@vger.kernel.org> # 3.8
  Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

  # This is the 10th commit message:

  ARM: 7661/1: mm: perform explicit branch predictor maintenance when required

  The ARM ARM requires branch predictor maintenance if, for a given ASID,
  the instructions at a specific virtual address appear to change.

  From the kernel's point of view, that means:

          - Changing the kernel's view of memory (e.g. switching to the
            identity map)
          - ASID rollover (since ASIDs will be re-allocated to new tasks)

  This patch adds explicit branch predictor maintenance when either of the
  two conditions above are met.

  Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
  Signed-off-by: Will Deacon <will.deacon@arm.com>
  Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Change-Id: I9d3f7512bdc8d9e7936a5fe17e3cddec2d59a953
Signed-off-by: JP Abgrall <jpa@google.com>